INSTALL_TARGET_PROCESSES = lockdownd

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = c0ntextomyrewind

c0ntextomyrewind_FILES = Tweak.x
c0ntextomyrewind_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
